name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFmNTFkOWUtODhjNi00NjQwLTg5OGQtMzAwN2QxNjZmNzRhIiwidGVuYW50X2lkIjoiM2Q5NTZhMDBhNDdiNDkzNGExYzFmMTI1YzNjOWY3NzFjMmI1ZTBjZWY1NDgzYzVhNWJhZjM4MDBlMzE5MzBkMiIsImludGVybmFsX3NlY3JldCI6IjA0YjFmYzg2LWM3N2YtNGUxNy04ZWZjLTIzODUwYWE1MDVlMSJ9._jkaiuOBM6btDEngsEFp9hGK87vw6pJ1AsSKx_s2viU"
JWT_SECRET = "secret"
 